apiVersion: apps/v1
kind: Deployment
metadata:
  name: pippo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: pippo
  template:
    metadata:
      labels:
        run: pippo