apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp
  namespace:
  labels:
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: webapp.cmp.local
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp
          servicePort: 80
